### ISSUE TITLE
Can't install anything

### ISSUE THREAD

**Issue by qxb3** [Yisus7u7/termux-pkg-manager#3]
![Screenshot_2021-09-13-19-44-58-021_com realvnc viewer android](https://user-images.githubusercontent.com/59109346/133077922-10d2a148-2fa4-49b1-8876-28c618c33601.jpg)

**Comment by JesusChapman** [comment]
Enter the package name correctly?

**Comment by qxb3** [comment]
> Enter the package name correctly?

Yes im just installing the number 1 on the list

**Comment by JesusChapman** [comment]
You must enter the name of the package in order to install it, not its number. 

Enter the package name in "enter package name"
